<?php
/**
 * Created by PhpStorm.
 * User: albert
 * Date: 12.03.15
 * Time: 22:23
 */

namespace common\component;


use common\helpers\Time;
use common\models\LogMain;
use yii\data\DataProviderInterface;
use yii\rest\Serializer;
use yii\web\Response;

class Controller extends \yii\web\Controller
{
	public function beforeAction($action)
	{
		/**
		 * @var $user \common\models\User
		 */
		$beforeAction = parent::beforeAction($action);
		if (!\Yii::$app->request->isAjax) {
			$log = new LogMain();
			$log->ip = \Yii::$app->request->getUserIP();
			$log->referrer = \Yii::$app->request->getReferrer();
			$log->method = \Yii::$app->request->getMethod();
			$log->action = $action->id;
			$log->controller = $this->id;
			$log->data = \Yii::$app->request->getBodyParams() ? json_encode(
				\Yii::$app->request->getBodyParams()
			) : null;
			$log->url = \Yii::$app->getRequest()->getAbsoluteUrl();
			$log->user_id = \Yii::$app->user->getId();
			$log->agent = \Yii::$app->request->getUserAgent();
			$log->robot = \Yii::$app->request->getIsRobot();
			$log->insert(false);
		}
		if (!\Yii::$app->user->isGuest) {
			$user = \Yii::$app->user->identity;
			//если пользователь не обновлялся более 60 секунд, то обновляем данные в объекте, но не делаем запрос в БД,
			// вдруг где то в контроллере уже делает апдейт, что бы не делать лишний запрос к БД
			if ($user->updated_at < time() - Time::SEC_TO_MINUTE) {
				$user->online = true;
				$user->created_at = time();
			};
		}
		return $beforeAction;
	}

	public function renderCollection(DataProviderInterface $interface)
	{
		$serializer = new Serializer();
		$serializer->collectionEnvelope = 'items';
		return $this->renderJson($serializer->serialize($interface));
	}

	public function afterAction($action, $result)
	{
		/**
		 * @var $user \common\models\User
		 */
		if (!\Yii::$app->user->isGuest) {
			$user = \Yii::$app->user->identity;
			// если у пользователя изменили данные и не сохранили, то сохраняем,
			// один из вариантов обновления без сохранения смотреть в методе чуть выше beforeAction
			if ($user->getDirtyAttributes()) {
				$user->update();
			}
		}
		return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
	}

	public function renderJson($data)
	{
		\Yii::$app->response->format = Response::FORMAT_JSON;
		return $data;
	}
}